module.exports.altArray = [
        {main: `AGC eXec`, alts: [`AGC feX`, "Log Hunters", "Test RSN68"]},
        {main: `aikuinen`, alts: [`tylleroxyeet`]},
        {main: `Albatrossse`, alts: [`hello bigboi`]},
        {main: `Bagelboiiiii`, alts: [`StaleBageI`]},
        {main: `BB Shrek`, alts: [`BB Plover`]},
        {main: `BB8`, alts: [`Crandor Dock`,`Arenys`,`nr-n99`]},
        {main: `BassMusic`, alts: [`Forestry CC`,`ForestryCC`]},
        {main: `bakkhant`, alts: [`Ardeinae`]},
        {main: `Chunky Verf`, alts: [`Alt Soul`,`Also Verf`]},
        {main: `Delibero`, alts: [`AllSeeingPie`, `LuvPeekR`, `LuvPeekL`]},
        {main: `Ecx`, alts: [`gorilla crap`, `mr ass eater`, `donkey crap`]},
        {main: `Entussy`, alts: [`Jay Sahn`, `Not Jay Sahn`, `JaySahnn`]},
        {main: `Evequill`, alts: [`Mxmmy Quill`,`Pinkeaux`,`Peacequill`,`Hikikomrxism`,`Group Quill`]}, 
        {main: `FoxyBaphomet`, alts: [`RNGeesus`, `Unclothed`, `SlootLoops`,`Razzmatazz`]},
        {main: `GamSlav`, alts: [`GamSlav Jr`,`G a m`, `Ga m`, `KrabSlayer69`, `c ra b`,`Live4Ever`]},
        {main: `HCpotatolegs`, alts: [`Potatolegs`, `matharamadev`, `GIMPot`, `k1dnam3dcud1`]},
        {main: `Jurrie`, alts: [`Jurphaas`]},
        {main: `Killerjj1196`, alts:[`IronJJ1196`]},
        {main: `KittyPuray`, alts:[`24broddi1093`]},
        {main: `Knightromite`, alts: [`Tiny nite`,`Knightrolite`,`Helping Nite`,`Helpinhands`,`inmy defense`]},
        {main: `kreeq`, alts: [`kreeq alt 1`,`kreeq alt 2`,`kreeq alt 3`,`kreeq alt 4`,`kreeq alt 5`,`kreeq alt 6`,`kreeq alt 7`,`kreeq alt 8`,`kreeq alt 9`]},
        {main: `MableLake`, alts: [`LoadedSwing`,`Creedle`,`FinalBossCEO`]},
        {main: `MapsquareBob`, alts: [`Bobstre`, ` WhyisBob`]},
        {main: `MasterPoke`, alts: [`Fe Killaman`,`Korosen sei`]},
        {main: `MrsMangione`, alts: [`Jess or Cyan`]},
        {main: `Nagoya`, alts: [`bianca`,`gsec`,`69d you`,`robin 48`,`baller melo8`]},
        {main: `POWER TRIP`, alts: [`Gravey ard`]},
        {main: `Rat Funk`, alts: [`Millnium`, `HEAVY TROOPA`, `Larpas`]},
        {main: `singl`, alts: [`buy limiter`, `buy limiting`, `Rat of Greed`]},
        {main: `Sol Heretit`, alts: [`Robinz hood`]},
        {main: `Superstition`, alts: [`ColumbusCrew`, `Chris Craft`]},
        {main: `Talviel`, alts: [`Olmanda`]},
        {main: `TikiTyler`, alts: [`RuneCape57`, `mr5775`]},
        {main: `Wideroe`, alts: [`Wiggly Wings`, `Aranwa`, `click baws`, `Mousekey`, `Iuned`, `Learjet 45`]},
        {main: `wides`, alts: [`Rides`]},
        {main: `yack daniels`, alts: [`re-frozen`]},
        {main: `Zam`, alts: [`Zaman`]},
      ];
